<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="FAIZAN-MF" failures="1" tests="1" name="Test" time="1.019" errors="0" timestamp="2024-04-05T21:27:08 IST">
  <testcase classname="dataProvider.DataProvider" name="login" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
at datafromexcel.ReadData.getexceldata(ReadData.java:51)
at dataproviderWith2class.Datautils.getData(Datautils.java:11)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Test -->
